/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayGameIdRouteImport } from './routes/play.$gameId'
import { Route as TemplatesSlugNewRouteImport } from './routes/templates.$slug.new'
import { Route as GamesGameIdEditRouteImport } from './routes/games.$gameId.edit'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGameIdRoute = PlayGameIdRouteImport.update({
  id: '/play/$gameId',
  path: '/play/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSlugNewRoute = TemplatesSlugNewRouteImport.update({
  id: '/$slug/new',
  path: '/$slug/new',
  getParentRoute: () => TemplatesRoute,
} as any)
const GamesGameIdEditRoute = GamesGameIdEditRouteImport.update({
  id: '/games/$gameId/edit',
  path: '/games/$gameId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/upload': typeof UploadRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/games/$gameId/edit': typeof GamesGameIdEditRoute
  '/templates/$slug/new': typeof TemplatesSlugNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/upload': typeof UploadRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/games/$gameId/edit': typeof GamesGameIdEditRoute
  '/templates/$slug/new': typeof TemplatesSlugNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/upload': typeof UploadRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/games/$gameId/edit': typeof GamesGameIdEditRoute
  '/templates/$slug/new': typeof TemplatesSlugNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/templates'
    | '/upload'
    | '/play/$gameId'
    | '/games/$gameId/edit'
    | '/templates/$slug/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/templates'
    | '/upload'
    | '/play/$gameId'
    | '/games/$gameId/edit'
    | '/templates/$slug/new'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/templates'
    | '/upload'
    | '/play/$gameId'
    | '/games/$gameId/edit'
    | '/templates/$slug/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  UploadRoute: typeof UploadRoute
  PlayGameIdRoute: typeof PlayGameIdRoute
  GamesGameIdEditRoute: typeof GamesGameIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$gameId': {
      id: '/play/$gameId'
      path: '/play/$gameId'
      fullPath: '/play/$gameId'
      preLoaderRoute: typeof PlayGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$slug/new': {
      id: '/templates/$slug/new'
      path: '/$slug/new'
      fullPath: '/templates/$slug/new'
      preLoaderRoute: typeof TemplatesSlugNewRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/games/$gameId/edit': {
      id: '/games/$gameId/edit'
      path: '/games/$gameId/edit'
      fullPath: '/games/$gameId/edit'
      preLoaderRoute: typeof GamesGameIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TemplatesRouteChildren {
  TemplatesSlugNewRoute: typeof TemplatesSlugNewRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesSlugNewRoute: TemplatesSlugNewRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  UploadRoute: UploadRoute,
  PlayGameIdRoute: PlayGameIdRoute,
  GamesGameIdEditRoute: GamesGameIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
